function gof = createFits(x, counts)
%CREATEFITS(X,COUNTS)
%  Create fits.
%
%  Data for 'untitled fit 2' fit:
%      X Input : x
%      Y Output: counts
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-May-2013 20:51:35


%% Fit: 'untitled fit 1'.
% Cannot generate code for fit 'untitled fit 1' because the data selection is incomplete.

%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x, counts );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( ft );

% Fit model to data.
[A, ~] = fit( xData, yData, ft);
y = reshape(coeffvalues(A),3,[]);
gof = diag(sqrt(sum(y.^2,2)).^(-1)) * y;
