function output_txt = labeldtips(obj,event_obj,f)
% Display an observation's Y-data and label for a data tip
% obj          Currently not used (empty)
% event_obj    Handle to event object
% xydata       Entire data matrix
% labels       State names identifying matrix row
% xymean       Ratio of y to x mean (avg. for all obs.)
% output_txt   Datatip text (string or string cell array)
% This datacursor callback calculates a deviation from the
% expected value and displays it, Y, and a label taken
% from the cell array 'labels'; the data matrix is needed
% to determine the index of the x-value for looking up the
% label for that row. X values could be output, but are not.

pos = get(event_obj,'Position');
x = pos(1); y = pos(2); t = pos(3);
formatSpec = '%+3.2e';
% sprintf('%-0.5e \t',A)
output_txt = {sprintf('p: (%1.1f \t , %1.1f \t )  t: %u',x,y,t),...
    '---------',...
    'Feautures:',...
    ['f(1): ',num2str(f(t,1),formatSpec), '     f(2): ',num2str(f(t,2),formatSpec)],...
    ['f(3): ',num2str(f(t,3),formatSpec), '     f(4): ',num2str(f(t,4),formatSpec)],...
    ['f(5): ',num2str(f(t,5),formatSpec), '     f(6): ',num2str(f(t,6),formatSpec)],...
    ['f(7): ',num2str(f(t,7),formatSpec), '     f(8): ',num2str(f(t,8),formatSpec)]};

% 
% output_txt = {['p: (',num2str(x),', ',num2str(y),')  t:',num2str(t)],...
%     '---------',...
%     'Feautures:',...
%     ['f(1): ',num2str(f(t,1),formatSpec), '    f(2): ',num2str(f(t,2),formatSpec)],...
%     ['f(3): ',num2str(f(t,3),formatSpec), '    f(4): ',num2str(f(t,4),formatSpec)],...
%     ['f(5): ',num2str(f(t,5),formatSpec), '    f(6): ',num2str(f(t,6),formatSpec)],...
%     ['f(7): ',num2str(f(t,7),formatSpec), '    f(8): ',num2str(f(t,8),formatSpec)]};
% 
% 
